name:                vandelay
version:             0.1.3.1
github:              "tumarkin/vandelay"
license:             BSD3
author:              "Robert Tumarkin"
maintainer:          "tumarkin@gmail.com"
copyright:           "2022 Robert Tumarkin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vandelay#readme>

dependencies:
- base >= 4.17 && < 5
- Glob 
- data-default-class
- dhall
- either
- file-embed
- mono-traversable
- mtl
- optparse-applicative 
- parsec
- parsec-numbers
- rainbow
- rio
- split
- string-interpolate
- transformers
- text
    
library:
  source-dirs: src

executables:
  vandelay:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vandelay

default-extensions:    
- ExplicitForAll
- FlexibleContexts
- LambdaCase
- MultiWayIf
- NoFieldSelectors
- NoImplicitPrelude
- OverloadedRecordDot
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- UnicodeSyntax
- ViewPatterns
